version: 2

aliases:      
  - &install-bundle-dependencies
    |
      bundle install

base_job: &base_job
  macos:
    xcode: "10.0.0"
  shell: /bin/bash --login -eo pipefail
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8

jobs:
  build-and-test:
    <<: *base_job

    steps:
      - checkout

      - run:
          name: Chruby
          command: chruby

      - run:
          name: Install bundled gems
          command: *install-bundle-dependencies

      - run:
          name: Run tests
          command: bundle exec fastlane tests --verbose

      - run:
          name: Danger
          command: bundle exec danger
          when: always

      - run:
          name: Generate test results
          command: cp fastlane/test_output/report.junit fastlane/test_output/results.xml
          when: always

      - store_test_results:
          path: fastlane/test_output

      - store_artifacts:
          path: fastlane/test_output
          destination: scan-test-results

      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
